services:
  - type: web
    name: fleet-php
    env: php
    rootDir: framework
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan route:clear
      php artisan view:clear
      php artisan cache:clear
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php -S 0.0.0.0:${PORT} -t public
